# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: surgeon

on:
  schedule:
    # Runs "At 00:01 every night" (UTC)
    - cron: '1 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Tools
      run: go install github.com/bketelsen/surgeon@v0.2.3

    - name: surgeon
      run: surgeon -v

    - name: index
      run: ./misc/index.sh
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with: 
        commit-message: pull upstream changes
        branch-suffix: random
        delete-branch: true
